# Generated by Django 5.2.7 on 2025-10-23 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_owner"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectvendor",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_assignments",
                to="projects.building",
            ),
        ),
        migrations.AddField(
            model_name="projectvendor",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="vendor_assignments", to="services.service"
            ),
        ),
    ]
