# Generated by Django 5.2.7 on 2025-10-23 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mas_sheets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mas",
            name="approval_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mas",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mas",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_mas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mas",
            name="review_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mas",
            name="review_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mas",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_mas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mas",
            name="revision",
            field=models.CharField(default="R0", editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name="mas",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("revision_requested", "Revision Requested"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
    ]
