# Generated by Django 5.2.7 on 2025-10-23 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mas_sheets",
            "0002_mas_approval_comment_mas_approval_date_mas_approver_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MASActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("edited", "Edited"),
                            ("submitted_review", "Submitted for Review"),
                            ("reviewed", "Reviewed"),
                            ("submitted_approval", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                            ("revision_submitted", "Revision Submitted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("details", models.TextField(blank=True)),
                ("project_name", models.CharField(blank=True, max_length=200)),
                ("building_name", models.CharField(blank=True, max_length=200)),
                ("service_name", models.CharField(blank=True, max_length=200)),
                ("item_name", models.CharField(blank=True, max_length=200)),
                ("make", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(blank=True, max_length=20)),
                (
                    "mas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="mas_sheets.mas",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MAS Activity Log",
                "verbose_name_plural": "MAS Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
