# Generated by Django 5.2.7 on 2025-10-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mas_sheets", "0003_masactivitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="mas",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mas",
            name="parent_mas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="mas_sheets.mas",
            ),
        ),
        migrations.AlterField(
            model_name="mas",
            name="mas_id",
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
