# Generated by Django 5.2.7 on 2025-10-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="level",
            field=models.CharField(
                choices=[("Creator", "Creator"), ("Approver", "Approver")],
                max_length=50,
            ),
        ),
    ]
