# Generated by Django 5.2.7 on 2025-10-23 02:15

from django.db import migrations
from django.contrib.auth import get_user_model

def update_user_permissions(apps, schema_editor):
    User = get_user_model()
    for user in User.objects.all():
        # Set staff status based on level
        if user.level in ['Admin', 'Approver']:
            user.is_staff = True
            
        # Set department for Creator level users
        if user.level == 'Creator':
            user.department = 'Vendor'
            user.is_staff = False
            
        # Make Admin users superusers
        if user.level == 'Admin':
            user.is_superuser = True
            
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_level'),
    ]

    operations = [
        migrations.RunPython(update_user_permissions, reverse_code=migrations.RunPython.noop),
    ]