# Generated by Django 5.2.7 on 2025-10-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20251023_update_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="level",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Creator", "Creator"),
                    ("Approver", "Approver"),
                    ("Reviewer", "Reviewer"),
                ],
                max_length=50,
            ),
        ),
    ]
