# Generated by Django 5.2.7 on 2025-10-23 07:13

from django.db import migrations, models


def convert_level_to_user_type(apps, schema_editor):
    """Convert old level values to new user_type"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for user in CustomUser.objects.all():
        if user.level == 'Admin':
            user.user_type = 'Admin'
        elif user.level in ['Reviewer', 'Approver', 'Creator']:
            user.user_type = 'Team'
        else:  # Default to Vendor
            user.user_type = 'Vendor'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Team", "Team"), ("Vendor", "Vendor")],
                default="Vendor",
                max_length=50,
            ),
        ),
        migrations.RunPython(convert_level_to_user_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="customuser",
            name="level",
        ),
    ]
